TeamManagement/Models/Team Page/TeamStructure.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Script.Serialization;
using Newtonsoft;
using DbIntegrationOracle;
using BusinessEntity;

namespace TeamManagement.Models.Team_Page
{
    public class MemberDetailsGet
    {

        public List<MemberDetails> lstgetMemDetails { get; set; }
        public int SaveStatus { get; set; }
    }

    public class TeamStructure
    {
        public List<TeamDetails> TeamTreeStructure { get; set; }

        public TeamStructure()
        {
            TeamTreeStructure = new List<TeamDetails>();
        }

        public List<TeamDetails> GetTeamDetails()
        {
            using (var entity = new OracleDBIntegrationEntities())
            {
                var teamDetailsList = (from team in entity.TEAMTBLs
                                       from user in entity.REGISTRATIONs
                                       where team.TEAMLEADID == user.ID
                                       select new TeamDetails
                                       {
                                           TeamId = team.TEAMID,
                                           TeamName = team.TEAMNAME,
                                           TeamLead = new UserDetails()
                                           {
                                               UserId = user.ID,
                                               UserName =
                                           user.FIRSTNAME + " " + user.LASTNAME
                                           },
                                           TeamMembers = (from members in entity.USERTEAMMAPPINGs
                                                          from users in entity.REGISTRATIONs
                                                          where team.TEAMID == members.TEAMID
                                                          && members.USERID == users.ID
                                                          select new UserDetails
                                                          {
                                                              UserId = members.USERID,
                                                              UserName = users.FIRSTNAME + " " + users.LASTNAME
                                                          }).ToList()
                                       }).ToList();

                TeamTreeStructure = teamDetailsList;
            }

            return TeamTreeStructure;
        }

        public void AddTeam(string pTeamName, decimal pTeamLeadId)
        {
            using (var entity = new OracleDBIntegrationEntities())
            {
                var newTeam = new TEAMTBL();
                decimal TopId = entity.TEAMTBLs.DefaultIfEmpty().Max(p => p == null ? 0 : p.TEAMID);
                newTeam.TEAMNAME = pTeamName;
                newTeam.TEAMLEADID = pTeamLeadId;
                newTeam.TEAMID = TopId + 1;
                entity.TEAMTBLs.Add(newTeam);
                entity.SaveChanges();
            }
        }

        public void AddMember(decimal pTeamId, string pMemberId)
        {

            using (var entity = new OracleDBIntegrationEntities())
            {
                string[] userid = pMemberId.Split(',');

                decimal TopId = entity.USERTEAMMAPPINGs.DefaultIfEmpty().Max(p => p == null ? 0 : p.MAPPINGID);
                for (int i = 0; i < userid.Length; i++)
                {

                    if (!string.IsNullOrEmpty(userid[i]))
                    {

                        var newMember = new USERTEAMMAPPING();
                        newMember.TEAMID = pTeamId;
                        newMember.MAPPINGID = TopId + 1;
                        newMember.USERID = Convert.ToInt32(userid[i]);
                        entity.USERTEAMMAPPINGs.Add(newMember);
                        TopId++;
                    }
                }

                entity.SaveChanges();

            }
        }

        public void TeamRename(decimal pTeamId, string pTeamRename)
        {
            using (var entity = new OracleDBIntegrationEntities())
            {
                var team = entity.TEAMTBLs.Where(x => x.TEAMID == pTeamId).FirstOrDefault();
                team.TEAMNAME = pTeamRename;
                entity.SaveChanges();
            }
        }

        public void DeleteMember(decimal pTeamId, decimal pMemberId)
        {
            using (var entity = new OracleDBIntegrationEntities())
            {
                var member = entity.USERTEAMMAPPINGs.Where(x => x.TEAMID == pTeamId && x.USERID == pMemberId).FirstOrDefault();
                entity.USERTEAMMAPPINGs.Remove(member);
                entity.SaveChanges();
            }
        }

        public void DeleteTeam(decimal pTeamId)
        {
            using (var entity = new OracleDBIntegrationEntities())
            {
                entity.USERTEAMMAPPINGs.Where(x => x.TEAMID == pTeamId).ToList().ForEach(i =>
                { entity.USERTEAMMAPPINGs.Remove(i); });

                var team = entity.TEAMTBLs.Where(x => x.TEAMID == pTeamId).FirstOrDefault();
                entity.TEAMTBLs.Remove(team);
                entity.SaveChanges();
            }
        }

    }

    public class TeamDetails
    {
        public decimal TeamId { get; set; }
        public string TeamName { get; set; }
        public UserDetails TeamLead { get; set; }
        public List<UserDetails> TeamMembers { get; set; }

        public TeamDetails()
        {
            TeamMembers = new List<UserDetails>();
        }

    }

    public class UserDetails
    {
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
    }

}

TeamManagement/Controllers/InternalTeamManagemetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamManagement.Models.Team_Page;
using DbIntegrationOracle;
using BusinessEntity;

namespace TeamManagement.Controllers
{
    public class InternalTeamManagemetController : Controller
    {
       
        MemberDetailsGet objMemDetails = new MemberDetailsGet();
        MemberDetailsGet objmemgetmdl = new MemberDetailsGet();
       
        public ActionResult GetDetails()
        {
            
            var teamStructure = new TeamStructure();
            teamStructure.TeamTreeStructure = teamStructure.GetTeamDetails();
            return View(teamStructure);
        }
        
        public ActionResult AddTeam(string pTeamName,decimal pTeamLeadId)
        {
            var teamStructure = new TeamStructure();
            teamStructure.AddTeam(pTeamName, pTeamLeadId);
            teamStructure.TeamTreeStructure = teamStructure.GetTeamDetails();

            return PartialView("_TeamStructure", teamStructure);
        }
        [HttpPost]
        public ActionResult AddTeamMember(decimal pTeamId,string pMemberIds)
        {
            var teamStructure = new TeamStructure();
            teamStructure.AddMember(pTeamId, pMemberIds);
            teamStructure.TeamTreeStructure = teamStructure.GetTeamDetails();

            return PartialView("_TeamStructure", teamStructure);
        }

        public void TeamRename(decimal pTeamId,string pTeamName)
        {
            new TeamStructure().TeamRename(pTeamId, pTeamName);
        }

        public void DeleteMember(decimal pTeamId,decimal pMemberId)
        {
            new TeamStructure().DeleteMember(pTeamId, pMemberId);
        }

        public void DeleteTeam(decimal pTeamId)
        {
            new TeamStructure().DeleteTeam(pTeamId);
        }
        public JsonResult GetMemberDetails(string Purpose,int TeamID)
        {
            
            IRepository ObjRepositary;
            ObjRepositary = new Repository();
            objmemgetmdl.lstgetMemDetails= ObjRepositary.GetMemeberInformations(TeamID);
            return Json(objmemgetmdl.lstgetMemDetails, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ReplaceTeamLeader(string Purpose, int TeamID,int NewTeamLeadID)
        {
            var teamStructure = new TeamStructure();
            IRepository ObjRepositary;
            ObjRepositary = new Repository();
            objmemgetmdl.SaveStatus = ObjRepositary.ReplaceTeamLeader(Purpose,TeamID,NewTeamLeadID);
            if (objmemgetmdl.SaveStatus == 1)
            {
                teamStructure.TeamTreeStructure = teamStructure.GetTeamDetails();

                return PartialView("_TeamStructure", teamStructure);
            }
            else
            {
                return Json(objmemgetmdl.SaveStatus, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

TeamManagement/Views/InternalTeamManagemet/GetDetails.cshtml
@model TeamManagement.Models.Team_Page.TeamStructure

@{
    ViewBag.Title = "TeanPage";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<script>
    var urlGetDropdownDetails = '@Url.Action("GetMemberDetails", "InternalTeamManagemet")';
    var urlReplaceTeamLead = '@Url.Action("ReplaceTeamLeader", "InternalTeamManagemet")';
    var UserID = '@Session["UserID"]'.toString();
</script>
<script src="~/js/jquery-ui.js"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/themes/default/style.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/jstree/3.0.9/jstree.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/Datatable.bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="~/Content/chosen.css" />
<script src="~/js/chosen.jquery.min.js"></script>
<script src="~/js/TeamPage.js"></script>
<div class="panel panel-primary style=" width:70%;height:100%;>
    <div id="teampageactions" style="padding-top:10px">

        <table id="tblTeam" align="center">
            <tr>
                <td>
                    <div id="addteam">


                        <input type="button" value="Add New Team" class="btn-success" />
                    </div>
                </td>
                <td>
                    <div id="deleteteam">
                        <input type="button" value="Delete Team" class="btn-danger" />

                    </div>
                </td>
                <td>
                    <div id="renameteam">
                        <input type="button" value="Rename Team" class="btn-primary" />

                    </div>
                </td>
                <td>
                    <div id="assignmember">
                        <input type="button" value="Add Member" class="btn-success" />

                    </div>
                </td>
                <td>
                    <div id="changeteamlead">
                        <input type="button" id="btnReplaceteamLead" value="Replace Team Lead" class="btn-primary" />

                    </div>
                </td>
                <td>
                    <div id="removemember">
                        <input type="button" value="Remove Member" class="btn-danger" />

                    </div>
                </td>
            </tr>
        </table>

    </div>
    <br />
    <table align="center">
        <tr>
            <td>
                <div class="panel panel-primary" style="width:600px;height:100%;min-height:450px;left: 50%;right:50%">

                    <div class="panel-heading">
                        Team Tree
                    </div>
                    <div id="teamstructure" style="width:600px;height:100%;min-height:450px;background-color:#d9edf7">
                        @Html.Partial("_TeamStructure", Model)
                    </div>
                </div>
            </td>

        </tr>
    </table>
</div>
<div id="divaddTeam">

    <div id="renameteam_dialog">

        <input type="text" id="renameteam_dialog_value" />
        <input type="button" value="Save" id="renameteam_dialog_save" />
    </div>

    <div id="addteam_dialog" style="align-content:center">
        <table>
            <tr>
                <td>
                    <label>Team Name </label>
                </td>
                <td>
                    <input id="teamname" type="text" /><br />
                </td>
            <tr>
            <tr>
                <td>
                    <label>Team Lead </label>
                </td>
                <td>

                    <select id="teamleadname" class="chosen-select" tabindex="8" style="width:160px;" data-placeholder="Select Team Lead">
                        <option value=""></option>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="button" value="Save" id="addteam_dialog_save" />
                </td>
            </tr>
        </table>

    </div>

    <div id="assignmember_dialog">
        <label> Member Name</label>
        <select id="membername" class="chosen-select" tabindex="8" multiple="" style="width:350px;" data-placeholder="Select Team Memebers">
            <option value=""></option>
        </select>
        <input type="button" id="assignmember_dialog_save" value="Save" />
    </div>
</div>
<div id="ReplaceTeamLeader" style="width:400px;height:500px; align-content:center">
    <table>

        <tr>
            <td>
                <label> Replace with</label>
            </td>
            <td>
                <select id="drpReplaceTeamLead" class="chosen-select" tabindex="8" style="width:200px;" data-placeholder="Select Team Memebers">
                    <option value=""></option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <input type="button" id="TeamLeaderChange_save" value="Save" />
            </td>
        </tr>

    </table>
</div>

TeamManagement/Views/InternalTeamManagemet/_TeamStructure.cshtml
@model TeamManagement.Models.Team_Page.TeamStructure

@foreach (var node in Model.TeamTreeStructure)
{
    <ul>
        <li class="teamname" data-teamid="@node.TeamId">
            @node.TeamName
            <ul>
                <li class="teamlead" data-teamleadid="@node.TeamLead.UserId">
                    @node.TeamLead.UserName
                    <ul>
                        @foreach (var teammember in node.TeamMembers)
                        {
                            <li class="teammumbers" data-teammemberid="@teammember.UserId">@teammember.UserName</li>
                        }
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
}