TeamManagement/Controllers/TaskManagementController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TeamManagement.Models;
using DbIntegrationOracle;
using System;
using TeamManagement;
using System.Data;


namespace BCBSTeamManagement.Controllers
{
    [SessionTimeOut]
    public class TaskManagementController : Controller
    {
        Integration objIng = new Integration();
        TaskManagementModel objTmnt = new TaskManagementModel();
        [System.Web.Mvc.OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult TaskManagement()
        {
            if (Convert.ToInt32(Session["UserSessionValid"]) == 1)

            {
                TeamUserDetails();
                return View(objTmnt); }
            else
            {
                
                return RedirectToAction("Login", "Login");

            }
        }
        public void TeamUserDetails()
        {
            objTmnt.UserID = Convert.ToInt32(Session["UserID"]);

            DataTable dt = objIng.GetTeamDetails(objTmnt.UserID);
            if (dt.Rows.Count>0)
            {
                objTmnt.TeamId = Convert.ToInt32(dt.Rows[0]["TeamId"]);
                objTmnt.TeamLeadId = Convert.ToInt32(dt.Rows[0]["TeamLeadId"]);
                Session["TeamLeadId"] = objTmnt.TeamLeadId;
                objTmnt.TeamName = dt.Rows[0]["TeamName"].ToString();
                objTmnt.TeamLeadName = dt.Rows[0]["TeamLeadName"].ToString();
            }
            else
            {
                objTmnt.TeamId = 0;
                objTmnt.TeamLeadId = 0;
                Session["TeamLeadId"] = 0;
                objTmnt.TeamName = "Not Assigned";
                objTmnt.TeamLeadName = "Not Assigned";

            }
            List<AssignedToAssignedByDetails> UserListDb = objIng.GetAssignedToDropdownDetails(objTmnt.TeamId, objTmnt.TeamLeadName);
            List<AssignedToAssignedByModel> UserList = new List<AssignedToAssignedByModel>();
            if (UserListDb != null)
            {
                foreach (AssignedToAssignedByDetails item in UserListDb)
                {
                    UserList.Add(new AssignedToAssignedByModel
                    {
                        FullName = item.FullName,
                        UserName = item.UserName
                    });
                }
            }
            objTmnt.UserDropDownList = UserList;
        }
        public JsonResult GetTaskDetails()
        {
            TaskManagementModel tobj = new TaskManagementModel();
            List<TaskManagement> parts = new List<TaskManagement>();
          
            return Json("");
        }
        [HttpPost]
        public PartialViewResult AddNewTask(TaskManagement pTask)
        {
            objTmnt.TaskDetailist = objTmnt.AddTaskDetail(pTask);
            var viewResult = PartialView("_GridRowForTaskManagement", objTmnt);
            return viewResult;

        }
        [HttpPost]
        public PartialViewResult EditTask(TaskManagement pTask)
        {
            objTmnt.EditTaskDetails(pTask);
            objTmnt.TaskDetailist = objTmnt.GetTasks();
            var viewResult = PartialView("_GridRowForTaskManagement", objTmnt);
             return viewResult;
            
        }

        [HttpGet]
        public PartialViewResult DeleteTask(int pTaskId)
        {
             objTmnt.DeleteTask(pTaskId);
            objTmnt.TaskDetailist = objTmnt.GetTasks();
            var viewResult = PartialView("_GridRowForTaskManagement", objTmnt);
            return viewResult;


        }
        [HttpGet]
        public PartialViewResult SearchTask(string username)   //Function to search task of particular user
        {

            objTmnt.TaskDetailist.Clear();
            if (username != "All")
            {
                List<TaskManagementDetails> Task = objIng.GetAllTasksForSelectedUser(username);

                if (Task != null)
                {
                    foreach (TaskManagementDetails item in Task)
                    {
                        objTmnt.TaskDetailist.Add(new TaskManagement
                        {
                            Id = Convert.ToInt32(item.Id),
                            TaskDescription = item.TaskDescription,
                            strStartDate = item.StartDate.Value.ToString("MM-dd-yyyy"),
                            strEndDate = item.EndDate.Value.ToString("MM-dd-yyyy"),
                            AssignedBy = item.AssignedBy,
                            AssignedTo = item.AssignedTo,
                            Status = item.Status,
                            Completion = item.Completion,

                        });
                    }
                }
            }
            else
            {
                objTmnt.TaskDetailist = objTmnt.GetTasks();
            }

            var viewResult = PartialView("_GridRowForTaskManagement", objTmnt);
            return viewResult;

        }

        public int Sonarerrorcheck()
        {
            int r =checkStatus()
    ?Convert.ToInt32(1)
    : Convert.ToInt32(1);

            return r;
        }
        public bool checkStatus()
        {
            return true;
        }
    }
}

TeamManagement/Views/TaskManagement/TaskManagement.cshtml
@model TeamManagement.Models.TaskManagementModel
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title> Task Management</title>
    <link href="~/Content/jquery-ui.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/excite-bike/jquery-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/chosen.css" />
    <script src="~/js/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/Datatable.bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css" />
    <script src="~/js/jquery.Datatable.min.js"></script>
    <script src="~/js/datatable.bootsrap.min.js"></script>
    <script src="~/js/chosen.jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/js/UserAccountManagement.js"></script>
    <script src="~/js/TaskManagement.js"></script>
    <script src="~/js/AddNewTaskValidation.js"></script>
    <script>
        var SaveImagePath = '@Model.SaveImagePath';
        var EditImagePath = '@Model.EditImagePath';
        var SessionTeamLeadID =@Session["TeamLeadId"].ToString();


        var UserDeleteUrl = '@Url.Action("DeleteTask", "TaskManagement")';

        var UserDeleteUrl = '@Url.Action("DeleteTask", "TaskManagement")';
    </script>
</head>

<body>

    <div class="panel panel-default" style="padding-right:10px ;padding-left:10px;padding-top:10px">
        <div class="container">

            <div class="alert alert-success hidden" id="successMessage">
                <strong>Success!</strong>
            </div>

            <div class="alert alert-danger hidden" id="errorMessage">
                <strong></strong>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-xs-9">
                    <label>Project Name: </label>
                    <label>@Model.TeamName </label>
                    <br />
                    <br />
                </div>
                <div class="col-xs-3">
                    <label>Team Lead: </label>
                    <label>@Model.TeamLeadName  </label>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-4">
                    <button type="button" class="btn btn-success" id="gridRowAdd">Add New Task</button>
                    <br />
                    <br />
                </div>
                <div class="col-xs-8" id="divForSelect">

                    <select id="selUser" data-placeholder="Choose a Person"
                            class="my_select_box" style="width:30%">
                        <option value="All">All</option>
                        @foreach (var e in Model.UserDropDownList)
                        {
                            <option value="@e.FullName">@e.FullName</option>
                        }
                    </select>
                    <br />
                    <br />
                </div>
            </div>
        </div>

        @if (Session["TeamLeadId"].ToString() == "0")
            {
            <div style="text-align:center">
                <label style="color:red; text-align:center">
                    Currently not assigned to any team. Kindly contact the administrator for team  assignment related queries
                </label>

            </div>
        }


        <div>


            <table id="TaskManagementDataTable" class="table table-striped table-bordered">
                <thead>
                    <tr class="success">
                        <th>TaskID</th>
                        <th>Task Description</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Assigned By</th>
                        <th>Assigned To </th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr class="success">
                        <th>TaskID</th>
                        <th>Task Description</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Assigned By</th>
                        <th>Assigned To </th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </tfoot>
                <tbody id="gridRowForTeamManagement">

                    @if (Session["TeamLeadId"].ToString() != "0")
                    {

                        @Html.Partial("_GridRowForTaskManagement", Model)
                    }



                </tbody>
            </table>
        </div>

        <form id="AddEditDialogForm">
            <div id="gridAddEditDialog">
                <div class="container">

                    <div class="alert alert-success hidden" id="DialogsuccessMessage">
                        <strong>Success!</strong>
                    </div>

                    <div class="alert alert-danger hidden" id="DialogerrorMessage">
                        <strong></strong>
                    </div>
                </div>
                <table class="table">
                    <tbody>
                        <tr class="success" id="TaskRow">
                            <td><label>Task ID </label></td>
                            <td><input type="text" id="gridAddEditDialog_txtTaskId" onkeypress="return isNumber(event)" /></td>
                        </tr>
                        <tr class="info">
                            <td><label>Task Description </label></td>
                            <td>
                                <textarea rows="5" cols="60" id="gridAddEditDialog_txtTaskDescription" maxlength="1500"></textarea>
                                <p id="counter"></p>
                            </td>
                        </tr>
                        <tr class="success">
                            <td><label>Start Date</label></td>
                            <td><input type="text" id="gridAddEditDialog_dtStartDate" maxlength="10" /></td>
                        </tr>
                        <tr class="info">
                            <td><label>End Date</label></td>
                            <td><input type="text" id="gridAddEditDialog_dtEndDate" maxlength="10" /></td>
                        </tr>
                        <tr class="success">
                            <td><label>Assigned By</label></td>
                            <td><input type="text" id="gridAddEditDialog_txtTaskAssignedBy" value="@Model.TeamLeadName" disabled="disabled" /></td>
                        </tr>
                        <tr class="info">
                            <td><label>Assigned To</label></td>
                            <td>
                                @if (Model.TeamLeadId == Model.UserID)
                                {
                                    <select id="SelAssignedTo" data-placeholder="Choose a Person"
                                            class="my_select_box" style="width:20%">
                                        @foreach (var e in Model.UserDropDownList)
                                        {
                                            <option value="@e.FullName">@e.FullName</option>
                                        }

                                    </select>
                                }
                                else
                                {
                                    <input type="text" id="gridAddEditDialog_txtTaskAssignedTo" value="@Session["UserFullName"].ToString()" disabled="disabled" />
                                }
                                @*<input type="text" id="gridAddEditDialog_txtTaskAssignedTo" onkeypress="return ValidateAlphabets(event)" />*@
                            </td>
                        </tr>
                        <tr class="success">
                            <td><label>Status</label></td>
                            <td>
                                <select id="gridAddEditDialog_txtTaskCompleted">
                                    <option value="1">Started</option>
                                    <option value="2">In-Progress</option>
                                    <option value="3">Review</option>
                                    <option value="4">Completed</option>
                                </select>
                            </td>
                        </tr>
                        <tr class="info">

                            <td colspan="2"><input type="button" class="btn btn-success" id="gridAddEditDialog_save" data-currentaction="" value="Save" /></td>
                        </tr>

                    </tbody>

                </table>

            </div>
        </form>
    </div>
</body>

TeamManagement/Views/TaskManagement/_GridRowForTaskManagement.cshtml
@model TeamManagement.Models.TaskManagementModel




@foreach (var item in Model.TaskDetailist.OrderByDescending(r => r.Id))
{
    <tr id="@(item.Id)_row">
        <td id="@(item.Id)_row_taskid">@item.Id</td>
        <td id="@(item.Id)_row_taskdescription">@item.TaskDescription</td>
        <td id="@(item.Id)_row_DtePicker_StartDate">@(item.strStartDate)</td>
        <td id="@(item.Id)_row_DtePicker_EndDate">@(item.strEndDate)</td>
        <td id="@(item.Id)_row_assignby">@item.AssignedBy</td>
        <td id="@(item.Id)_row_assignto">@item.AssignedTo</td>

        <td id="@(item.Id)_row_status">@item.Status</td>
        <td>

            <table>
                @if (item.AssignedTo == Session["UserFullName"].ToString() || Session["TeamLeadId"].ToString() == Session["UserID"].ToString())
                {
                    Model.Flag = "";
                }
                else
                {
                    Model.Flag = "cursor: not-allowed";
                    // EditReadonlyids = EditReadonlyids+ item.Id+ "_row_edit" + ",";
                    // DeleteReadonlyids = DeleteReadonlyids + item.Id + "_row_delete" + ",";
                }

                <tr>

                    <td id="img@(item.Id)">
                        <img src="@Url.Content(Model.EditImagePath)" alt="Edit" title='Edit' class="clsEditRow" id="@(item.Id)_row_edit" style="@Model.Flag" />
                    </td>
                    <td>
                        <img src="../Images/1458311125_DeleteRed.png" alt="Delete" title="Delete" class="clsDeleteTask"
                             id="@(item.Id)_row_delete" style="@Model.Flag" />
                    </td>
                </tr>
            </table>
        </td>
    </tr>

}